# Generated by Django 3.2.13 on 2022-08-09 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartPizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_order.cart')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_order.pizza')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='pizza',
            field=models.ManyToManyField(through='pizza_order.CartPizza', to='pizza_order.Pizza'),
        ),
    ]
