# Generated by Django 3.2.13 on 2022-08-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_order', '0004_auto_20220810_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpizza',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderpizza',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
