# Generated by Django 3.2.13 on 2022-08-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_order', '0005_auto_20220812_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_idd',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
