# Generated by Django 3.2.13 on 2022-08-31 12:05

from django.db import migrations, models
import django.db.models.deletion
import pizza_order.models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_order', '0010_cartpizza_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_level', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=pizza_order.models.get_default_status, on_delete=django.db.models.deletion.CASCADE, to='pizza_order.status'),
        ),
    ]
