# Generated by Django 3.2.13 on 2022-09-02 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_order', '0014_order_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_order.order')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_order.status')),
            ],
        ),
    ]
