# Generated by Django 3.2.13 on 2022-09-02 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_order', '0015_statuslog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statuslog',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='statuslog',
            old_name='status_id',
            new_name='status',
        ),
    ]
