# Generated by Django 3.2.13 on 2022-08-30 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_shopkeeper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_shopkeeper',
            new_name='is_shop_owner',
        ),
    ]
